# Generated by Django 4.2 on 2025-01-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(default='00000000000', max_length=11),
        ),
    ]
