# Generated by Django 4.2 on 2025-02-09 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_contact_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(70)])),
                ('role', models.CharField(choices=[('manager', 'Restaurant Manager'), ('assistant_manager', 'Assistant Manager'), ('chef', 'Chef'), ('sous_chef', 'Sous Chef'), ('waiter', 'Waiter/Waitress'), ('bartender', 'Bartender'), ('cashier', 'Cashier'), ('delivery', 'Delivery Driver')], max_length=18)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
            ],
        ),
    ]
