# Generated by Django 4.2 on 2025-02-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='biography',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
