# Generated by Django 4.2 on 2025-02-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_employee_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile',
            field=models.ImageField(default='profiles/default.jpg', upload_to='profiles/'),
        ),
    ]
