# Generated by Django 4.2 on 2025-03-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
