# Generated by Django 4.2 on 2025-03-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='table_number',
            field=models.IntegerField(choices=[('number', '11'), ('number', '22'), ('number', '33'), ('number', '44'), ('number', '55'), ('number', '66'), ('number', '77'), ('number', '88'), ('number', '99')]),
        ),
    ]
