# Generated by Django 4.2 on 2025-03-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_reservation_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='table_number',
            field=models.CharField(choices=[('number', '11'), ('number', '22'), ('number', '33'), ('number', '44'), ('number', '55'), ('number', '66'), ('number', '77'), ('number', '88'), ('number', '99')], max_length=6),
        ),
    ]
