# Generated by Django 4.2 on 2025-02-02 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='phone_number',
        ),
    ]
